import "../../public/plugins/bootstrap/bootstrap.min.css";
import "../../public/plugins/animate-css/animate.css";
import "../../public/plugins/fontawesome/css/all.min.css";
import "../../public/plugins/slick/slick.css";
import "../../public/plugins/slick/slick-theme.css";
import "../../public/plugins/colorbox/colorbox.css";
import "./assets/scss/style.scss";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <script src="./plugins/jQuery/jquery.min.js" defer></script>
        <script src="./plugins/bootstrap/bootstrap.min.js" defer></script>
        <script src="./plugins/slick/slick.min.js" defer></script>
        <script src="./plugins/slick/slick-animation.min.js" defer></script>
        <script src="./plugins/colorbox/jquery.colorbox.js" defer></script>
        <script src="./plugins/shuffle/shuffle.min.js" defer></script>
        <script src="./plugins/shuffle/shuffle.min.js" defer></script>
        <script src="./plugins/js/script.js" defer></script>
      </body>
    </html>
  );
}
