name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js and pnpm
        uses: pnpm/setup-pnpm@v2  # Use the pnpm setup action
        with:
          version: 6  # Specify the pnpm version you want to use

      - name: Install Dependencies
        run: pnpm install

      - name: Build Next.js Application
        run: pnpm run build

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          echo "machine github.com login $GITHUB_ACTOR password $GITHUB_TOKEN" > ~/.netrc
          npx gh-pages -d out -b gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}